### ISSUE TITLE
v0.7.6 doesn't show the UI of the debugger 

### ISSUE THREAD

**Issue by ahmedmigo** [skpm/sketch-dev-tools#36]
Since I updated to the last version and run the plugin it doesn't show the web view.
Console shows
TypeError: null is not an object (evaluating 't.plugin.urlForResourceNamed("icon.png").path')
line: 199
sourceURL: /Users/ahmedgenaidy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/dev-tools.sketchplugin/Contents/Sketch/show-debugger.js
column: 421
stack: /Users/ahmedgenaidy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/dev-tools.sketchplugin/Contents/Sketch/show-debugger.js:199:421
./src/run-script.js@/Users/ahmedgenaidy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/dev-tools.sketchplugin/Contents/Sketch/show-debugger.js:199:1429
n@/Users/ahmedgenaidy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/dev-tools.sketchplugin/Contents/Sketch/show-debugger.js:1:173
./src/show-debugger.js@/Users/ahmedgenaidy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/dev-tools.sketchplugin/Contents/Sketch/show-debugger.js:203:528
n@/Users/ahmedgenaidy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/dev-tools.sketchplugin/Co<…>

**Comment by mathieudutour** [comment]
I just published 0.7.7 which might fix this. Could you report back?

**Comment by DhvanilPatel** [comment]
I've tried 0.7.7 with Sketch 52.2. It still doesn't show the web-view.

**Comment by mathieudutour** [comment]
what's the error in the logs?

**Comment by ahmedmigo** [comment]
still not working, and there is nothing appear in the log
NSThread.mainThread().threadDictionary()["skpm.debugger"] there is NSPanel but the webview doesn't shown until now

**Comment by ahmedmigo** [comment]
is this log related to dev-tool plugin ?
[C33 Hostname#aa74a0fc:443 tcp, url: https://gate.hockeyapp.net/v2/track, tls] cancelled
	[C33.1 <private> 172.16.3.3:56636<->IPv4#48b1ecf8:443]
	Connected Path: satisfied (Path is satisfied), interface: en3, ipv4, dns
	Duration: 61.206s, DNS @0.000s took 0.049s, TCP @0.052s took 0.020s, TLS took 0.096s
	bytes in/out: 7317/1653, packets in/out: 7/4, rtt: 0.018s, retransmitted packets: 0, out-of-order packets: 0

**Comment by ahmedmigo** [comment]
I added all the log that happens when I run the plugin, I hope it is helpful 
[dev-tools log.zip](https://github.com/skpm/sketch-dev-tools/files/2509933/dev-tools.log.zip)

**Comment by DhvanilPatel** [comment]
Hopefully this might help:
[dev-tools log.zip](https://github.com/skpm/sketch-dev-tools/files/2509971/dev-tools.log.zip)

I'm on MacOS version 10.14 (18A391)

**Comment by mathieudutour** [comment]
That was really weird: it worked fine when I had the plugin symlinked but I soon as I moved it to the plugins folder, it broke because the webview didn't want to load local files 🤔 .

Anyhow, v0.7.8 should fix it

**Comment by DhvanilPatel** [comment]
It works perfectly now – Thanks so much!

**Comment by ahmedmigo** [comment]
it works thank youu
